### PR TITLE
fix tag and profile endpoints

### PR DESCRIPTION
**Pull request by romainmenke**

### CODE REVIEW

**Comment by romainmenke** [comment]
Is there someone who can verify the output, I don't have a reference point.

**Comment by pieterbeulque** [comment]
A `GET /profile/cfda` should have this structure:

```js
{
  media: {
    nodes: [
      { thumbnail_src, code, display_src },
      { thumbnail_src, code, display_src },
      …
    ]
  }
}```

**Comment by romainmenke** [comment]
https://gist.github.com/romainmenke/5ffd8c0253e4d6639cf4e3d6805a5d18

That is the full profile page output, seems to have changed a lot.

**Comment by pieterbeulque** [comment]
Yes, your changes are correct but we'll have to update the implementation on clients too, which sucks 🙂 

CFDA does `res.data.media.nodes` but we'll need `res.data. edge_owner_to_timeline_media.edges` now, and update every `code` mention to `shortcode`.

🙃

**Pull request merged**
